import type { AgentConfig } from "./types";

export const AGENT_CONFIGS: Record<string, AgentConfig> = {
  tiktok: {
    title: "TikTok Textos",
    description: "Scripts virales de 2-4 min sobre narcisismo, apego y sanación",
    agentCount: 10,
    outputType: "Scripts .md",
    icon: "🎵",
    accent: "rose",
    greeting: "¡Hola! Soy el agente de TikTok. ¿Sobre qué tema quieres crear un script viral?",
    fields: [
      { name: "tema", label: "Tema del video", type: "textarea", placeholder: "Ej: Por qué no puedo dejarlo aunque me hace daño", required: true },
      { name: "categoria", label: "Categoría", type: "select", required: true, options: [
        { value: "narcisismo", label: "Narcisismo" },
        { value: "apego", label: "Apego" },
        { value: "nina_interior", label: "Niña Interior" },
        { value: "recuperacion", label: "Recuperación" },
        { value: "trauma_bonding", label: "Trauma Bonding" },
      ]},
      { name: "tipo", label: "Tipo", type: "select", options: [
        { value: "individual", label: "Individual" },
        { value: "serie", label: "Serie" },
      ]},
    ],
    steps: [
      "Orquestador: planificando",
      "Investigador: consultando base de conocimiento",
      "Viral TikTok: optimizando para viralidad",
      "Depurador: limpiando formato",
      "Descripciones: generando caption + hashtags",
      "Voiceover: adaptando para lectura en voz alta",
      "Contador: verificando palabras y duración",
    ],
  },
  emails: {
    title: "Email Marketing",
    description: "Emails HTML de alto impacto emocional",
    agentCount: 4,
    outputType: "Emails .html",
    icon: "📧",
    accent: "amber",
    greeting: "¡Hola! Vamos a crear un email de impacto. ¿Qué tipo de email necesitas?",
    fields: [
      { name: "tipo_email", label: "Tipo de email", type: "select", required: true, options: [
        { value: "bienvenida", label: "Bienvenida" },
        { value: "invitacion", label: "Invitación" },
        { value: "recordatorio", label: "Recordatorio" },
        { value: "info", label: "Informativo" },
      ]},
      { name: "audiencia", label: "Audiencia", type: "select", required: true, options: [
        { value: "clientas", label: "Clientas" },
        { value: "leads", label: "Leads" },
      ]},
      { name: "tema", label: "Tema", type: "text", required: true, placeholder: "Ej: Clase de apego ansioso" },
      { name: "fecha_clase", label: "Fecha de clase", type: "text", placeholder: "Ej: 25 de marzo" },
      { name: "link_cta", label: "Link del CTA", type: "text", placeholder: "https://..." },
    ],
    steps: [
      "Director: creando brief creativo",
      "Redactor: escribiendo el email",
      "Corrector: revisión de calidad",
      "Diseñador HTML: formateando",
    ],
  },
  voiceover: {
    title: "Voiceover Psicológico",
    description: "Voiceovers de 3 partes (~37,500 caracteres) para lives",
    agentCount: 3,
    outputType: "Voiceovers .md/.pdf",
    icon: "🎙️",
    accent: "violet",
    greeting: "¡Hola! Vamos a crear un voiceover de alto impacto emocional. ¿Qué tema quieres tratar?",
    fields: [
      { name: "tema", label: "Tema", type: "select", required: true, options: [
        { value: "1", label: "1. Cómo Detectar a un Narcisista" },
        { value: "2", label: "2. El Vínculo Traumático" },
        { value: "3", label: "3. Apego Ansioso y Narcisismo" },
        { value: "4", label: "4. TEPT Complejo en Relaciones" },
        { value: "5", label: "5. La Niña Interior Herida" },
        { value: "6", label: "6. Personas Vitamina vs Tóxicas" },
        { value: "7", label: "7. Gaslighting" },
        { value: "8", label: "8. Love Bombing" },
        { value: "9", label: "9. Codependencia Emocional" },
        { value: "10", label: "10. Ciclo del Abuso" },
        { value: "11", label: "11. Desintoxicación Emocional" },
        { value: "12", label: "12. Dependencia Emocional" },
        { value: "13", label: "13. Reconstruir Autoestima" },
        { value: "14", label: "14. Reparentalización" },
        { value: "15", label: "15. Contacto Cero" },
        { value: "custom", label: "Tema personalizado" },
      ]},
      { name: "tema_custom", label: "Tema personalizado", type: "textarea", placeholder: "Describe el tema que quieres tratar..." },
    ],
    steps: [
      "Parte 1: Generando contenido",
      "Parte 1: Agente ortográfico",
      "Parte 1: Verificando caracteres",
      "Parte 1: Revisor emocional",
      "Parte 2: Generando contenido",
      "Parte 2: Agente ortográfico",
      "Parte 2: Verificando caracteres",
      "Parte 2: Revisor emocional",
      "Parte 3: Generando contenido",
      "Parte 3: Agente ortográfico",
      "Parte 3: Verificando caracteres",
      "Parte 3: Revisor emocional",
      "Generando PDF final",
    ],
  },
  talleres: {
    title: "Talleres Vivenciales",
    description: "Talleres de 90 min con metáforas y dinámicas",
    agentCount: 7,
    outputType: "Guión + Mapa + Material",
    icon: "🎭",
    accent: "emerald",
    greeting: "¡Hola! Vamos a crear un taller vivencial. ¿Cuál es el tema central?",
    fields: [
      { name: "tema", label: "Tema del taller", type: "textarea", required: true, placeholder: "Ej: Rompiendo el ciclo del apego ansioso" },
      { name: "version", label: "Versión", type: "select", options: [
        { value: "v2", label: "v2 (Actual)" },
        { value: "v1", label: "v1 (Clásica)" },
      ]},
      { name: "categoria_metafora", label: "Tipo de metáfora", type: "select", options: [
        { value: "auto", label: "Automática" },
        { value: "naturaleza", label: "Naturaleza" },
        { value: "humana", label: "Humana" },
        { value: "arquitectonica", label: "Arquitectónica" },
        { value: "cuento", label: "Cuento" },
      ]},
    ],
    steps: [
      "Orquestador: analizando tema",
      "Investigador: consultando base de conocimiento",
      "Metáfora: creando historia central",
      "Estructura: diseñando los 5 bloques",
      "Escritor: redactando guión",
      "Calidad: validando contenido",
      "Generando mapa del taller",
      "Generando material de participante",
      "Exportando PDFs",
    ],
  },
  clases: {
    title: "Clases en Vivo",
    description: "Guiones completos para clases del programa Apego Detox",
    agentCount: 7,
    outputType: "Guiones .md/.pdf",
    icon: "📚",
    accent: "sky",
    greeting: "¡Hola! Vamos a crear una clase en vivo. ¿Qué clase necesitas?",
    fields: [
      { name: "clase_num", label: "Número de clase", type: "select", required: true, options: [
        { value: "1", label: "Clase 1" },
        { value: "2", label: "Clase 2" },
        { value: "3", label: "Clase 3" },
        { value: "custom", label: "Personalizada" },
      ]},
      { name: "comando", label: "Comando", type: "select", options: [
        { value: "completo", label: "Completo" },
        { value: "dolor", label: "Solo Dolor" },
        { value: "storytelling", label: "Solo Storytelling" },
        { value: "producto", label: "Solo Producto" },
        { value: "cta", label: "Solo CTA" },
        { value: "guion", label: "Solo Guión" },
        { value: "slides", label: "Solo Slides" },
      ]},
      { name: "brief", label: "Brief adicional", type: "textarea", placeholder: "Instrucciones adicionales..." },
    ],
    steps: [
      "DOLOR: mapeando puntos emocionales",
      "STORYTELLING: generando historias",
      "PRODUCTO: definiendo beneficios",
      "CTA: creando llamados a acción",
      "ESTRUCTURA: ensamblando guión",
      "SLIDES: generando diapositivas",
      "VALIDACIÓN: control de calidad",
    ],
  },
  cursos: {
    title: "Cursos Educativos",
    description: "Programas estructurados sobre psicología relacional",
    agentCount: 7,
    outputType: "Programas HTML/PDF",
    icon: "🎓",
    accent: "orange",
    greeting: "¡Hola! Vamos a crear un curso educativo. ¿Qué tema quieres enseñar?",
    fields: [
      { name: "tema", label: "Tema del curso", type: "textarea", required: true, placeholder: "Ej: Programa de 4 semanas sobre apego seguro" },
      { name: "fase", label: "Fase", type: "select", options: [
        { value: "completo", label: "Completo" },
        { value: "investigacion", label: "Solo investigación" },
        { value: "escritura", label: "Solo escritura" },
      ]},
    ],
    steps: [
      "Director: coordinando",
      "Investigador: analizando tema",
      "Profesor: diseñando contenido",
      "Emocional: agregando capa emocional",
      "Escritor: redactando",
      "Organizador: estructurando",
      "Calidad: validando",
      "Generando HTML/PDF",
    ],
  },
  libros: {
    title: "Libros Amazon & Hotmart",
    description: "Libros completos de 30,000+ palabras para autopublicación",
    agentCount: 8,
    outputType: "Manuscritos .md/.pdf",
    icon: "📖",
    accent: "teal",
    greeting: "¡Hola! Vamos a crear un libro completo. ¿Sobre qué tema quieres escribir?",
    fields: [
      { name: "tema", label: "Tema del libro", type: "textarea", required: true, placeholder: "Ej: Guía completa para sobrevivir al narcisismo" },
      { name: "titulo", label: "Título sugerido", type: "text", placeholder: "Opcional" },
      { name: "fase", label: "Fase", type: "select", options: [
        { value: "full", label: "Completo" },
        { value: "investigation", label: "Solo investigación" },
        { value: "architecture", label: "Solo arquitectura" },
        { value: "writing", label: "Solo escritura" },
        { value: "editing", label: "Solo edición" },
      ]},
      { name: "plataforma", label: "Plataforma", type: "select", options: [
        { value: "kdp", label: "Amazon KDP" },
        { value: "hotmart", label: "Hotmart" },
        { value: "ambas", label: "Ambas" },
      ]},
    ],
    steps: [
      "Investigador: analizando fuentes",
      "Arquitecto: diseñando estructura",
      "Escritor: redactando capítulos",
      "Editor: revisando y editando",
      "KDP Expert: optimizando",
      "Fact Checker: verificando datos",
      "Generando manuscrito final",
      "Exportando PDF",
    ],
  },
  sora: {
    title: "Sora Prompts",
    description: "Prompts cinematográficos de 15s para videos con Sora (OpenAI)",
    agentCount: 5,
    outputType: "Prompts .md",
    icon: "🎬",
    accent: "fuchsia",
    greeting: "¡Hola! Vamos a crear un prompt para Sora. ¿Modo dolor o invitación a clase?",
    fields: [
      { name: "modo", label: "Modo", type: "select", required: true, options: [
        { value: "dolor", label: "Dolor" },
        { value: "invitacion", label: "Invitación a clase" },
      ]},
      { name: "concepto", label: "Concepto del video", type: "textarea", required: true, placeholder: "Ej: La mujer no puede dejar de pensarlo, ansiedad extrema" },
      { name: "tono", label: "Tono emocional", type: "select", required: true, options: [
        { value: "explosivo_raw", label: "Explosivo / Raw" },
        { value: "demoledor", label: "Demoledor" },
        { value: "grito_silencioso", label: "Grito silencioso" },
        { value: "despertador", label: "Despertador" },
        { value: "incendiario", label: "Incendiario" },
        { value: "implosion", label: "Implosión" },
        { value: "ironico_provocador", label: "Irónico / Provocador" },
        { value: "empatico_sanador", label: "Empático / Sanador" },
        { value: "complice_oscuro", label: "Cómplice oscuro" },
        { value: "maestro_callejero", label: "Maestro callejero" },
        { value: "hielo", label: "Hielo" },
        { value: "poetico_crudo", label: "Poético crudo" },
      ]},
      { name: "formato", label: "Formato", type: "select", options: [
        { value: "9:16 vertical", label: "9:16 Vertical" },
        { value: "16:9 horizontal", label: "16:9 Horizontal" },
        { value: "1:1 cuadrado", label: "1:1 Cuadrado" },
      ]},
    ],
    steps: [
      "Analizador: descomponiendo concepto visual",
      "Director Visual: creando dirección cinematográfica",
      "Compositor: escribiendo prompt principal",
      "Optimizador: refinando y validando",
      "Variaciones: generando alternativas creativas",
    ],
  },
};
